[[redirects]]
  from = "/*"
  to = "https://blog-backend-oitprm1e0-vitaliikalinbets-projects.vercel.app"
  status = 200
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
