name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: npm install -g npm@latest
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.PERSONAL_NPM_ACCESS_TOKEN_FOR_BLOG}}" > .npmrc
      - name: Log token
        run: echo "${{secrets.PERSONAL_NPM_ACCESS_TOKEN_FOR_BLOG}}"
      - name: Log token
        run: echo "${{secrets.PERSONAL_NPM_ACCESS_TOKEN_FOR_BLOG}}"
      - name: Log npm version
        run: echo "npm -v"
      - name: Log node version
        run: echo "node -v"
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci
